### ISSUE TITLE
R2: open data, ex of revisiting old data sets

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#36]
>- “Revisiting old data sets using innovative techniques can support or contradict past narrative conclusions (e.g., Casillas, 2021).”
--> It would be useful to elaborate this in a few sentences and present the Casillas (2021) study in terms of revisiting old data sets and drawing (new?) conclusions.

TODO

- [x] briefly describe Casillas 2021 (meta analysis of 'compromise categories' in early bilinguals)

**Comment by IvanAndreuRascon** [comment]
Revisiting old data sets using innovative techniques can support or contradict past narrative conclusions (e.g., Casillas, 2021).” In this study, a meta-analysis of existing research on compromise voice-onset time (VOT) in early bilinguals—a phenomenon where bilinguals are thought to produce speech sounds intermediate between those of monolingual speakers of each language—was conducted. By systematically re-evaluating prior data and incorporating new acoustic analyses of coronal stops from early Spanish–English bilinguals, the study found that the cumulative evidence for "compromise" VOT was negligible. Instead of having merged phonetic categories, early bilinguals exhibited performance mismatches due to dynamic interlingual interactions elicited by the experimental tasks. This reanalysis not only contradicted earlier conclusions but also provided a more in-depth understanding of bilingual speech production.

**Comment by jvcasillas** [comment]
Added via https://github.com/RAP-group/guide_to_open_science/commit/df3696cb69af90c98f54c435e2332d5c81a57ba3
