### ISSUE TITLE
R2: open data, ling is WEIRD

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#37]
> - “Open data are particularly important for the field of linguistics, for all of the aforementioned reasons, and also because linguistics is Western, Educated, Industrialized, Rich, and Democratic (WEIRD, Bochynska et al., 2023).”
--> I do not disagree, in principle, but there may be one caveat that needs to be mentioned: Bochynska et al. (2023) evaluated publications written in English. This seems slightly self- selecting to me, as it probably excludes relevant linguistic research traditions whose main language of publication is not English (e.g. Chinese linguistics). How sure can we then be that linguistics as a whole is WEIRD? I suggest the authors tone down this statement a bit, as it seems too strong in its current form.

TODO

- [ ] Fine. Tone it down by hedging.. something like "some linguists have described the field of linguistics as being WEIRD"

**Comment by RobertEspo** [comment]
Option 1: Open data are particularly important for the field of linguistics, for all of the aforementioned reasons, and also because some linguists have described the state of the field as being Western, Educated, Industrialized, Rich and Democratic (WEIRD, Bochynska et al., 2023).

Option 2: Open data are particularly important for the field of linguistics, for all of the aforementioned reasons, and also because some linguists have described the state of the field, as far as English-language publications are concerned, as being Western, Educated, Industrialized, Rich and Democratic (WEIRD, Bochynska et al., 2023).

**Comment by jvcasillas** [comment]
Went with option 2, added additional refs via https://github.com/RAP-group/guide_to_open_science/commit/2fdd07076a1d55713eddf7b6a834ffb07e5cf577
