### ISSUE TITLE
R2: open data, unique challenges in linguistics

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#39]
> - “Having stated all the above, it is necessary to recognize that the field of linguistics faces unique challenges with regard to open data.”
--> Are these necessarily unique challenges? I do not think it is important to point this out (and I am not sure if linguistics really faces unique challenges that different from other related disciplines). What would be more important is to go into more detail about which areas of linguistics face which types of challenges, since there are so many different types of data that we as linguists work with (experimental data, corpus data, data from grammars, data from linguistic databases, written, spoken, signed data, historical data, and each oft these types could be distinguished further). This should be discussed in much more detail and made more concrete so that the readers can see their approaches / types of data represented in this discussion.

TODO

- [x] I think we are saying the same things... ling poses unique challenges because of the rich variety in subfields that all do things differently... rephrase to make R2 happy

**Comment by RobertEspo** [comment]
Having stated all the above, it is necessary to recognize that linguistics faces a unique challenge with its multitude of subfields that work with a variety of data formats. Due to the diversity, one must determine which aspects of open science are relevant to their data.

(I think this is sufficient since the rest of the paragraph goes into a bunch of examples.)

**Comment by jvcasillas** [comment]
Added via https://github.com/RAP-group/guide_to_open_science/commit/2f335c95f4c00995c89408c686ba8dee5a7cb841
