### ISSUE TITLE
R2: open data, move/restructure

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#42]
> - “When primary data, such as audio or video files, cannot be shared, derived data in the form of tabular files can take its place...”
--> This paragraph is very important and constructive. Different types of data (primary data vs. processed data and annotations) should be introduced at the beginning of this section, though, and the entire section should be more precise about what types of data particular arguments refer to.

TODO

- [x] We cannot have every point moved to the beginning...
- [x] We need to write down the general outline of this section and consider how to restructure at a more macro level (rather than moving a few pieces around)

**Comment by stephanierod** [comment]
Include the novelty of preregistration across disciplines as noted in (Bochynska et al. 2023) for example in behavioral sciences. However, noting the mentioned rarity for advocacy for preregistration in linguistics because of time lag. Furthermore, recognizing the differences between exploratory and confirmatory research (Plonsky and Brysbaert, 2024). Lastly, the need for transparency in regards to publication biases referring to the frequency of statistically significant research being published over studies with null results. Should we also include the time of peer review, if it happens pre- or post- data collection?

**Comment by stephanierod** [comment]
Haven and van Grootel (2019) and Haven
et al., (2020) argued that preregistration can also be useful for qualitative
researchers. OSF has provided a template for qualitative researchers along with
additional resources https://osf.io/j7ghv/.

**Comment by stephanierod** [comment]
All materials, protocols, data, analysis code, and
manuscript versions are publicly available via the following link on OSF:
https://osf.io/4j5cr/.

**Comment by jvcasillas** [comment]
Generally addressed via https://github.com/RAP-group/guide_to_open_science/pull/64
