### ISSUE TITLE
R2: reproducibility, lack of inclusivity

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#52]
> - “There are several steps that researchers can take to make their code and projects more
reproducible.”
--> A large portion of linguistic work is qualitative and does not rely on any code. If the paper is meant to be relevant to all linguistic approaches in general, please be more inclusive. Alternatively, the topic of the paper could be specified more and refer to “quantitative linguistics”?

TODO

- [ ] add language explaining (again) that this is not all fields... a "where applicable" type hedging

**Comment by RobertEspo** [comment]
In linguistics there is increasing awareness of the importance of reproducibility, and many researchers are beginning to take steps to improve the reproducibility of their research. **For quantitative reseach**, there are several steps that researchers can take to make their code and projects more reproducible. One approach is to create reports that document the research process by including descriptions of the data, the methods used to analyze the data, and the results.

Since this chunk of the paper is about code, I just limited it to quantitative research as the reviewer suggested.

**Comment by jvcasillas** [comment]
Added via https://github.com/RAP-group/guide_to_open_science/commit/d273c7632aa0c3c7460f3483aac25bcdab67abc1
